routes/web.php
<?php

//Route::get('/users/logout', 'Auth\LoginController@userLogout')->name('logout');

Auth::routes();

Route::get('/', 'Front\DashboardController@index')->name('front.index');
Route::get('/boardGames', 'Front\BoardGamesController@index')->name('front.board_games.index');
Route::get('/shoppingLists', 'Front\ShoppingListsController@index')->name('front.shopping_lists.index');


Route::prefix('admin')->group(function()
{
    Route::get('login', 'Auth\AdminLoginController@loginForm')->name('admin.login');
    Route::post('login', 'Auth\AdminLoginController@login')->name('admin.login.submit');
    Route::get('logout', 'Auth\AdminLoginController@logout')->name('admin.logout');

    Route::get('/', 'Admin\DashboardController@index')->name('admin.dashboard');

    Route::resource('account','Admin\AccountController', AdminRouteHelper::RouteResource('account'));

    Route::post('urls/filters', 'Admin\UrlsController@filters')->name('admin.urls.filters.submit');
    Route::post('urls/ajaxCheckUrl', 'Admin\UrlsController@ajaxCheckUrl')->name('admin.urls.ajaxCheckUrl');
    Route::post('urls/ajaxGenerateUrl', 'Admin\UrlsController@ajaxGenerateUrl')->name('admin.urls.ajaxGenerateUrl');
    Route::post('urls/ajaxGetMenu', 'Admin\UrlsController@ajaxGetMenu')->name('admin.urls.ajaxGetMenu');
    Route::resource('urls','Admin\UrlsController', AdminRouteHelper::RouteResource('urls'));

    Route::resource('pages','Admin\PagesController', AdminRouteHelper::RouteResource('pages'));

    Route::post('menus/ajaxGetMenus', 'Admin\MenusController@ajaxGetMenus')->name('admin.menus.ajaxGetMenus');
    Route::resource('menus','Admin\MenusController', AdminRouteHelper::RouteResource('menus'));
    Route::resource('modules','Admin\ModulesController', AdminRouteHelper::RouteResource('modules'));
    Route::resource('admins','Admin\UsersAdminsController', AdminRouteHelper::RouteResource('admins'));


    // ----

    Route::resource('notes','Admin\NotesController', AdminRouteHelper::RouteResource('notes'));
    Route::resource('notesGroups','Admin\NotesGroupsController', AdminRouteHelper::RouteResource('notes_groups'));
    Route::post('shoppingLists/filters', 'Admin\ShoppingListsController@filters')->name('admin.shopping_lists.filters.submit');
    Route::post('shoppingLists/search', 'Admin\ShoppingListsController@search')->name('admin.shopping_lists.search.submit');
    Route::post('shoppingLists/ajaxQuantityPriority', 'Admin\ShoppingListsController@ajaxQuantityPriority')->name('admin.shopping_lists.ajax_quantity_priority.submit');
    Route::get('shoppingLists/upDown/{action}/{id}', 'Admin\ShoppingListsController@upDown')->name('admin.shopping_lists.up_down');
    Route::resource('shoppingLists','Admin\ShoppingListsController', AdminRouteHelper::RouteResource('shopping_lists'));
    Route::resource('shoppingListsShops','Admin\ShoppingListsShopsController', AdminRouteHelper::RouteResource('shopping_lists_shops'));
    Route::resource('boardGames','Admin\BoardGamesController', AdminRouteHelper::RouteResource('board_games'));
    Route::post('boardGames/filters', 'Admin\BoardGamesController@filters')->name('admin.board_games.filters.submit');
    Route::resource('boardGamesPlays','Admin\BoardGamesPlaysController', AdminRouteHelper::RouteResource('board_games_plays'));
    Route::post('boardGamesPlays/filters', 'Admin\BoardGamesPlaysController@filters')->name('admin.board_games_plays.filters.submit');
    Route::get('boardGamesPlays/filtersGame/{id}', 'Admin\BoardGamesPlaysController@filtersGame')->name('admin.board_games_plays.filters.game');
    Route::resource('boardGamesPlayers','Admin\BoardGamesPlayersController', AdminRouteHelper::RouteResource('board_games_players'));
    Route::resource('boardGamesStats','Admin\BoardGamesStatsController', AdminRouteHelper::RouteResource('board_games_stats'));
    Route::post('boardGamesStats/filters', 'Admin\BoardGamesStatsController@filters')->name('admin.board_games_stats.filters.submit');
    Route::resource('payments','Admin\PaymentsController', AdminRouteHelper::RouteResource('payments'));
});

app/Modules.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class Modules extends Authenticatable
{
    use Notifiable;

    protected $guard = 'admin';

    protected $fillable = 
    [
        'name', 'class', 'symbol', 'singleton'
    ];

    public static function getModules($array = false, $ajax = false)
    {
        $db = Modules::all();
        $modules = [];

        foreach($db as $module)
        {
            if(empty($array))
            {
                $modules[$module->id] = $module->name;
            }
            else
            {
                $modules[$module->id] = 
                [
                    'name' => $module->name,
                    'available' => true // jesli singleton to trzeba kontrolowac czy moze byc dołaczony
                ];
            }
        }

        return $modules;
    }

    public static function getModuleIdBySymbol($symblol)
    {
        $module = Modules::where('symbol', '=', $symblol)->first();
        
        return !empty($module) ? $module->id : null;
    }
}

app/Http/Controllers/Admin/ModulesController.php
<?php

namespace App\Http\Controllers\Admin;

use Auth;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Facades\Validator;
use Illuminate\Validation\Rule;
use App\Http\Controllers\AdminController;
use App\Modules;

class ModulesController extends AdminController
{
    public function __construct()
    {
        $this->middleware('auth:admin');

        parent::__construct('modules');
    }

    public function index()
    {
        $this->init();

        $app = $this->app;
        $grid = Modules::paginate(10);

        return view('admin.modules.index', compact('app', 'grid'));
    }

    public function create(Request $request)
    {
        $this->init();
        $app = $this->app;

        return view('admin.modules.create', compact('app'));
    }

    public function store(Request $request)
    {
        $messages = $this->validatorMessages(
        [
            'name.required', 
            'symbol.required',
        ]);

        $validator = Validator::make($request->all(), 
        [
            'name' => 'required',
            'symbol' => 'required',
        ], $messages);

        if ($validator->fails()) 
        {
            return redirect()->back()->withErrors($validator)->withInput();
        }
        
        $input = $request->all();
        $languages = Modules::create($input);
        
        return redirect()->route('admin.modules.edit', ['id' => $languages->id])->with('success','Wpis dodany pomyślnie');
    }

    public function edit($id)
    {
        $this->init();

        $app = $this->app;
        $edit = Modules::find($id);

        return view('admin.modules.edit', compact('app', 'edit'));
    }

    public function update($id, Request $request)
    {
        $messages = $this->validatorMessages(
        [
            'name.required', 
            'symbol.required',
        ]);

        $validator = Validator::make($request->all(), 
        [
            'name' => 'required',
            'symbol' => 'required',
        ], $messages);

        if ($validator->fails()) 
        {
            return redirect()->back()->withErrors($validator)->withInput();
        }

        $input = $request->all();

        $modules = Modules::find($id);
        $modules->update($input);

        return redirect()->route('admin.modules.edit', ['id' => $modules->id])->with('success','Wpis zaktualizowany pomyślnie');
    }

    public function destroy($id)
    {
        //TODO: Weryfikacja

        if(true == true)
        {
            $modules = Modules::find($id);
            $modules->delete();

            return redirect()->route('admin.modules.index')->with('success', 'Wpis został usunięty');
        }
        else
        {
            return redirect()->route('admin.modules.index')->with('error', 'Istnieją wpisy powiązane z tym menu.');
        }
    }
}

resources/views/admin/modules/create.blade.php
@extends('admin.layout')

@section('content')

    <form method="POST" action="{{ route('admin.modules.create.submit') }}">
        @csrf
        <div class="card-body white-background silver-border radius-border-top">

            <div class="form-group {{ AdminHelper::DisplayErrorsClass($errors, 'name', 'input-error jq-input-error') }}">
                <label for="name">Nazwa</label>
                <input type="text" class="form-control" id="name" name="name" placeholder="" value="{{ old('name') }}">
            </div>

            <div class="form-group {{ AdminHelper::DisplayErrorsClass($errors, 'class', 'input-error jq-input-error') }}">
                <label for="email">Klasa</label>
                <input type="text" class="form-control" id="class" name="class" placeholder="" value="{{ old('class') }}">
            </div>

            <div class="form-group {{ AdminHelper::DisplayErrorsClass($errors, 'symbol', 'input-error jq-input-error') }}">
                <label for="email">Symbol</label>
                <input type="text" class="form-control" id="symbol" name="symbol" placeholder="" value="{{ old('symbol') }}">
            </div>

            <div class="form-group">
                <label for="email">Pojedynczy</label>
                <select class="form-control" name="singleton">
                    <option value="0">Nie</option>
                    <option value="1">Tak</option>
                </select>
            </div>

        </div>
        <div class="card-footer silver-border radius-border-bottom">
            <button type="submit" class="btn btn-primary">Zapisz</button>
        </div>
    </form>

@endsection

resources/views/admin/modules/edit.blade.php
@extends('admin.layout')

@section('content')

    <form method="POST" action="{{ route('admin.modules.edit.submit', $edit->id) }}">
        @csrf
        <input name="_method" type="hidden" value="PUT">
        <div class="card-body white-background silver-border radius-border-top">

            <div class="form-group {{ AdminHelper::DisplayErrorsClass($errors, 'name', 'input-error jq-input-error') }}">
                <label for="name">Nazwa</label>
                <input type="text" class="form-control" id="name" name="name" placeholder="" value="{{ !empty(old('name')) ? old('name') : $edit->name }}">
            </div>

            <div class="form-group {{ AdminHelper::DisplayErrorsClass($errors, 'class', 'input-error jq-input-error') }}">
                <label for="email">Klasa</label>
                <input type="text" class="form-control" id="class" name="class" placeholder="" value="{{ !empty(old('class')) ? old('class') : $edit->class }}">
            </div>

            <div class="form-group {{ AdminHelper::DisplayErrorsClass($errors, 'symbol', 'input-error jq-input-error') }}">
                <label for="email">Symbol</label>
                <input type="text" class="form-control" id="symbol" name="symbol" placeholder="" value="{{ !empty(old('symbol')) ? old('symbol') : $edit->symbol }}">
            </div>

            <div class="form-group">
                <label for="email">Pojedynczy</label>
                <select class="form-control" name="singleton">
                    <option value="0" @if(0 == $edit->singleton) selected @endif>Nie</option>
                    <option value="1" @if(1 == $edit->singleton) selected @endif>Tak</option>
                </select>
            </div>

        </div>
        <div class="card-footer silver-border radius-border-bottom">
            <button type="submit" class="btn btn-primary">Zapisz</button>
        </div>
    </form>

@endsection

resources/views/admin/modules/index.blade.php
@extends('admin.layout')

@section('content')

    <table class="table table-grid radius-border">
        <tbody>
            <tr>
                <th>Nazwa</th>
                <th>Klasa</th>
                <th>Symbol</th>
                <th></th>
            </tr>
            @foreach ($grid as $key => $item)
            <tr>
                <td>{{ $item->name }}</td>
                <td>{{ $item->class }}</td>
                <td>{{ $item->symbol }}</td>
                <td class="text-right">
                    <a class="btn btn-sm btn-primary" href="{{ route('admin.modules.edit', $item->id) }}" title="Edytuj"><i class="fas fa-pencil-alt"></i></a>
                    <a class="btn btn-sm btn-danger jq-popup-congrim" data-submit-class="jq-delete-items-form-{{ $item->id }}" href="#" title="Usuń"><i class="fas fa-trash-alt"></i></a>
                    <form method="POST" action="{{ route('admin.modules.destroy', $item->id) }}" class="jq-delete-items-form-{{ $item->id }}">
                        <input name="_method" type="hidden" value="DELETE">
                        @csrf
                    </form>
                </td>
            </tr>
            @endforeach
        </tbody>
    </table>

    {{ $grid->render() }}

@endsection