routes/web.php
<?php

//Route::get('/users/logout', 'Auth\LoginController@userLogout')->name('logout');

Auth::routes();

Route::get('/', 'Front\DashboardController@index')->name('front.index');
Route::get('/boardGames', 'Front\BoardGamesController@index')->name('front.board_games.index');
Route::get('/shoppingLists', 'Front\ShoppingListsController@index')->name('front.shopping_lists.index');


Route::prefix('admin')->group(function()
{
    Route::get('login', 'Auth\AdminLoginController@loginForm')->name('admin.login');
    Route::post('login', 'Auth\AdminLoginController@login')->name('admin.login.submit');
    Route::get('logout', 'Auth\AdminLoginController@logout')->name('admin.logout');

    Route::get('/', 'Admin\DashboardController@index')->name('admin.dashboard');

    Route::resource('account','Admin\AccountController', AdminRouteHelper::RouteResource('account'));

    Route::post('urls/filters', 'Admin\UrlsController@filters')->name('admin.urls.filters.submit');
    Route::post('urls/ajaxCheckUrl', 'Admin\UrlsController@ajaxCheckUrl')->name('admin.urls.ajaxCheckUrl');
    Route::post('urls/ajaxGenerateUrl', 'Admin\UrlsController@ajaxGenerateUrl')->name('admin.urls.ajaxGenerateUrl');
    Route::post('urls/ajaxGetMenu', 'Admin\UrlsController@ajaxGetMenu')->name('admin.urls.ajaxGetMenu');
    Route::resource('urls','Admin\UrlsController', AdminRouteHelper::RouteResource('urls'));

    Route::resource('pages','Admin\PagesController', AdminRouteHelper::RouteResource('pages'));

    Route::post('menus/ajaxGetMenus', 'Admin\MenusController@ajaxGetMenus')->name('admin.menus.ajaxGetMenus');
    Route::resource('menus','Admin\MenusController', AdminRouteHelper::RouteResource('menus'));
    Route::resource('modules','Admin\ModulesController', AdminRouteHelper::RouteResource('modules'));
    Route::resource('admins','Admin\UsersAdminsController', AdminRouteHelper::RouteResource('admins'));


    // ----

    Route::resource('notes','Admin\NotesController', AdminRouteHelper::RouteResource('notes'));
    Route::resource('notesGroups','Admin\NotesGroupsController', AdminRouteHelper::RouteResource('notes_groups'));
    Route::post('shoppingLists/filters', 'Admin\ShoppingListsController@filters')->name('admin.shopping_lists.filters.submit');
    Route::post('shoppingLists/search', 'Admin\ShoppingListsController@search')->name('admin.shopping_lists.search.submit');
    Route::post('shoppingLists/ajaxQuantityPriority', 'Admin\ShoppingListsController@ajaxQuantityPriority')->name('admin.shopping_lists.ajax_quantity_priority.submit');
    Route::get('shoppingLists/upDown/{action}/{id}', 'Admin\ShoppingListsController@upDown')->name('admin.shopping_lists.up_down');
    Route::resource('shoppingLists','Admin\ShoppingListsController', AdminRouteHelper::RouteResource('shopping_lists'));
    Route::resource('shoppingListsShops','Admin\ShoppingListsShopsController', AdminRouteHelper::RouteResource('shopping_lists_shops'));
    Route::resource('boardGames','Admin\BoardGamesController', AdminRouteHelper::RouteResource('board_games'));
    Route::post('boardGames/filters', 'Admin\BoardGamesController@filters')->name('admin.board_games.filters.submit');
    Route::resource('boardGamesPlays','Admin\BoardGamesPlaysController', AdminRouteHelper::RouteResource('board_games_plays'));
    Route::post('boardGamesPlays/filters', 'Admin\BoardGamesPlaysController@filters')->name('admin.board_games_plays.filters.submit');
    Route::get('boardGamesPlays/filtersGame/{id}', 'Admin\BoardGamesPlaysController@filtersGame')->name('admin.board_games_plays.filters.game');
    Route::resource('boardGamesPlayers','Admin\BoardGamesPlayersController', AdminRouteHelper::RouteResource('board_games_players'));
    Route::resource('boardGamesStats','Admin\BoardGamesStatsController', AdminRouteHelper::RouteResource('board_games_stats'));
    Route::post('boardGamesStats/filters', 'Admin\BoardGamesStatsController@filters')->name('admin.board_games_stats.filters.submit');
    Route::resource('payments','Admin\PaymentsController', AdminRouteHelper::RouteResource('payments'));
});

resources/views/admin/_partials/_scripts.blade.php
<script>
    var csrfToken = '{{ csrf_token() }}';
    var ajaxGetMenusPostUrl = '{{ route('admin.menus.ajaxGetMenus') }}';
    var ajaxGenerateUrlPostUrl = '{{ route('admin.urls.ajaxGenerateUrl') }}';
    var ajaxCheckUrlPostUrl = '{{ route('admin.urls.ajaxCheckUrl') }}';
    var ajaxGetMenuPostUrl = '{{ route('admin.urls.ajaxGetMenu') }}';
</script>

<script src="{{ asset('assets/admin/js/admin.js') }}"></script>

<script>
    $.widget.bridge('uibutton', $.ui.button)
</script>

resources/views/admin/_partials/alerts.blade.php
@if ($message = Session::get('success'))
	<div class="alert alert-success alert-dismissible fade show" role="alert">
		{{ $message }}
		<button type="button" class="close" data-dismiss="alert" aria-label="Close">
		  <span aria-hidden="true">&times;</span>
		</button>
	</div>
@endif

@if ($message = Session::get('error'))
	<div class="alert alert-danger alert-dismissible fade show" role="alert">
		{{ $message }}
		<button type="button" class="close" data-dismiss="alert" aria-label="Close">
		  <span aria-hidden="true">&times;</span>
		</button>
	</div>
@endif
	
@if (count($errors) > 0)
	<div class="alert alert-danger alerts-top">
		<strong>Uwaga!</strong> Wypełnij poprawnie wszystkie pola:
		<ul>
			@foreach ($errors->all() as $error)
				<li>{{ $error }}</li>
			@endforeach
		</ul>
	</div>
@endif

resources/views/admin/_partials/breadcrumb.blade.php
<div class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-10">
                <h1 class="m-0 text-dark">@if(!empty($app['current']['title'])) {{ $app['current']['title'] }} @endif</h1>
            </div>
            <div class="col-sm-2">
                <div class="float-sm-right">
                    @if(!empty($app['buttons']['create']))
                        <a class="btn btn-primary" href="{{ $app['buttons']['create'] }}" title="Dodaj nowy element"><i class="fas fa-plus"></i></a>
                    @endif
                    @if(!empty($app['buttons']['index']))
                        <a class="btn btn-default" href="{{ $app['buttons']['index'] }}" title="Dodaj nowy element"><i class="fas fa-bars"></i></a>
                    @endif
                </div>

                {{--
                <ol class="breadcrumb float-sm-right">

                    @foreach($app['breadcrumbs'] as $breadcrumb)
                        <li class="breadcrumb-item @if($breadcrumb['active'] == true) active @endif">

                            @if($breadcrumb['active'] == false) <a href="{{ $breadcrumb['route'] }}"> @endif

                                {{ $breadcrumb['name'] }}

                            @if($breadcrumb['active'] == false) </a> @endif
                        </li>
                    @endforeach

                </ol>
                --}}
            </div>

            @if(empty($app['search']))
                <div class="col-sm-12">
            @else
               <div class="col-sm-9">
            @endif
                    @include('admin._partials.filters')
               </div>

            @if(!empty($app['search']))
                <div class="col-sm-3">
                    @include('admin._partials.search')
                </div>
            @endif

        </div>
    </div>
 </div>

resources/views/admin/_partials/filters.blade.php
@if(!empty($app['filters']))

    <div class="filters">

        <div class="filters-label">Filtruj: </div>

        @foreach($app['filters'] as $key => $filter)
            <div class="filters-item">
                <form method="POST" action="{{ $filter['route'] }}">
                 @csrf
                    <select class="form-control jq-on-change-submit" name="{{ $key }}" id="{{ $key }}">
                        <option value="">{{ $filter['default'] }}</option>

                        @foreach($filter['items'] as $key => $item)
                            @if(empty($filter['name']))
                                <option value="{{ $key }}" @if($key == $filter['selected']) selected @endif >{{ $item }}</option>
                            @else
                                <option value="{{ $key }}" @if($key == $filter['selected']) selected @endif >{{ $filter['name'] }}: {{ $item }}</option>
                            @endif
                        @endforeach
                    </select>
                </form>
            </div>
        @endforeach

    </div>

@endif

resources/views/admin/_partials/navbar.blade.php
<nav class="main-header navbar navbar-expand navbar-white navbar-light">
    <ul class="navbar-nav">
        <li class="nav-item">
            <a class="nav-link" data-widget="pushmenu" href="#"><i class="fas fa-bars"></i></a>
        </li>
        <li class="nav-item d-none d-sm-inline-block">
          <a href="{{ route('admin.account.edit', $app['user']['id']) }}" class="nav-link">Moje konto</a>
        </li>
    </ul>
    <ul class="navbar-nav ml-auto">
      <li class="nav-item">
          <a class="logout-link" href="{{ route('admin.logout') }}">Wyloguj <i class="fas fa-sign-out-alt"></i></a>
      </li>
    </ul>
</nav>

resources/views/admin/_partials/search.blade.php
@if(!empty($app['search']))

    <div class="search">
        <form method="POST" action="{{ $app['buttons']['search'] }}">
            @csrf

            <div class="float-sm-right" style="margin-left: 4px;">
                <a class="btn btn-warning jq-on-click-submit" href="#" title="Szukaj"><i class="fas fa-search"></i></a>
            </div>
            <div class="float-sm-right">
                <input type="text" class="form-control" name="search" placeholder="Szukaj" value="{{$app['searchString']}}" />
            </div>

        </form>
    </div>

@endif

resources/views/admin/_partials/sidebar.blade.php
<aside class="main-sidebar sidebar-dark-primary elevation-4">
    <a href="http://www.arteh.pl" target="_blank" class="brand-link">
        <img src="{{ asset('assets/admin/images/arteh.png') }}" alt="ARTEHCMS" class="brand-image">
        <span class="brand-text">ARTEH</span><span class="brand-text font-weight-light">CMS</span>
    </a>

    <div class="sidebar">
      <div class="user-panel mt-3 pb-3 mb-3">
        <div class="image">
          <a href="{{ route('admin.account.edit', $app['user']['id']) }}">
            <img src="{{ ImageHelper::Thumb($app['user']['avatar'], 50, 50) }}" class="img-circle" alt="{{ $app['user']['name'] }}">
          </a>
        </div>
        <div class="info">
          <a href="{{ route('admin.account.edit', $app['user']['id']) }}" class="d-block">{{ $app['user']['name'] }}</a>
        </div>
      </div>

        <nav class="mt-2">
            <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
                @foreach ($app['menu'] as $parent)
                    @if($parent['visible'] == true)
                        <li class="nav-item @if(!empty($parent['children'])) has-treeview @endif @if($parent['active'] == true) menu-open @endif ">
                            <a href="{{ $parent['route'] }}" class="nav-link @if($parent['active'] == true) active @endif ">
                                @if(!empty($parent['icon']))
                                    <i class="nav-icon fas {{ $parent['icon'] }}"></i>
                                @endif
                                <p>
                                    {{ $parent['name'] }}
                                    @if(!empty($parent['children']))
                                        <i class="fas fa-angle-left right"></i>
                                    @endif
                                </p>
                            </a>
                            @if(!empty($parent['children']))
                                <ul class="nav nav-treeview" style="background-color: rgba(255,255,255,.05); border-radius: 5px;">
                                    @foreach ($parent['children'] as $child)
                                        @if($child['visible'] == true)
                                            <li class="nav-item">
                                                <a href="{{ $child['route'] }}" class="nav-link @if($child['active'] == true) active @endif ">
                                                    @if(!empty($child['icon']))
                                                        <i class="nav-icon fas {{ $child['icon'] }} "></i>
                                                    @endif
                                                    <p>
                                                        {{ $child['name'] }}
                                                    </p>
                                                </a>
                                            </li>
                                        @endif
                                    @endforeach
                                </ul>
                            @endif
                        </li>
                    @endif
                @endforeach
            </ul>
        </nav>
    </div>
</aside>