routes/web.php
<?php

//Route::get('/users/logout', 'Auth\LoginController@userLogout')->name('logout');

Auth::routes();

Route::get('/', 'Front\DashboardController@index')->name('front.index');
Route::get('/boardGames', 'Front\BoardGamesController@index')->name('front.board_games.index');
Route::get('/shoppingLists', 'Front\ShoppingListsController@index')->name('front.shopping_lists.index');


Route::prefix('admin')->group(function()
{
    Route::get('login', 'Auth\AdminLoginController@loginForm')->name('admin.login');
    Route::post('login', 'Auth\AdminLoginController@login')->name('admin.login.submit');
    Route::get('logout', 'Auth\AdminLoginController@logout')->name('admin.logout');

    Route::get('/', 'Admin\DashboardController@index')->name('admin.dashboard');

    Route::resource('account','Admin\AccountController', AdminRouteHelper::RouteResource('account'));

    Route::post('urls/filters', 'Admin\UrlsController@filters')->name('admin.urls.filters.submit');
    Route::post('urls/ajaxCheckUrl', 'Admin\UrlsController@ajaxCheckUrl')->name('admin.urls.ajaxCheckUrl');
    Route::post('urls/ajaxGenerateUrl', 'Admin\UrlsController@ajaxGenerateUrl')->name('admin.urls.ajaxGenerateUrl');
    Route::post('urls/ajaxGetMenu', 'Admin\UrlsController@ajaxGetMenu')->name('admin.urls.ajaxGetMenu');
    Route::resource('urls','Admin\UrlsController', AdminRouteHelper::RouteResource('urls'));

    Route::resource('pages','Admin\PagesController', AdminRouteHelper::RouteResource('pages'));

    Route::post('menus/ajaxGetMenus', 'Admin\MenusController@ajaxGetMenus')->name('admin.menus.ajaxGetMenus');
    Route::resource('menus','Admin\MenusController', AdminRouteHelper::RouteResource('menus'));
    Route::resource('modules','Admin\ModulesController', AdminRouteHelper::RouteResource('modules'));
    Route::resource('admins','Admin\UsersAdminsController', AdminRouteHelper::RouteResource('admins'));


    // ----

    Route::resource('notes','Admin\NotesController', AdminRouteHelper::RouteResource('notes'));
    Route::resource('notesGroups','Admin\NotesGroupsController', AdminRouteHelper::RouteResource('notes_groups'));
    Route::post('shoppingLists/filters', 'Admin\ShoppingListsController@filters')->name('admin.shopping_lists.filters.submit');
    Route::post('shoppingLists/search', 'Admin\ShoppingListsController@search')->name('admin.shopping_lists.search.submit');
    Route::post('shoppingLists/ajaxQuantityPriority', 'Admin\ShoppingListsController@ajaxQuantityPriority')->name('admin.shopping_lists.ajax_quantity_priority.submit');
    Route::get('shoppingLists/upDown/{action}/{id}', 'Admin\ShoppingListsController@upDown')->name('admin.shopping_lists.up_down');
    Route::resource('shoppingLists','Admin\ShoppingListsController', AdminRouteHelper::RouteResource('shopping_lists'));
    Route::resource('shoppingListsShops','Admin\ShoppingListsShopsController', AdminRouteHelper::RouteResource('shopping_lists_shops'));
    Route::resource('boardGames','Admin\BoardGamesController', AdminRouteHelper::RouteResource('board_games'));
    Route::post('boardGames/filters', 'Admin\BoardGamesController@filters')->name('admin.board_games.filters.submit');
    Route::resource('boardGamesPlays','Admin\BoardGamesPlaysController', AdminRouteHelper::RouteResource('board_games_plays'));
    Route::post('boardGamesPlays/filters', 'Admin\BoardGamesPlaysController@filters')->name('admin.board_games_plays.filters.submit');
    Route::get('boardGamesPlays/filtersGame/{id}', 'Admin\BoardGamesPlaysController@filtersGame')->name('admin.board_games_plays.filters.game');
    Route::resource('boardGamesPlayers','Admin\BoardGamesPlayersController', AdminRouteHelper::RouteResource('board_games_players'));
    Route::resource('boardGamesStats','Admin\BoardGamesStatsController', AdminRouteHelper::RouteResource('board_games_stats'));
    Route::post('boardGamesStats/filters', 'Admin\BoardGamesStatsController@filters')->name('admin.board_games_stats.filters.submit');
    Route::resource('payments','Admin\PaymentsController', AdminRouteHelper::RouteResource('payments'));
});

app/Notes.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Database\Eloquent\Model;
use App\NotesGroups;

class Notes extends Model
{
    use Notifiable;

    protected $guard = 'admin';
    protected $table = 'notes';

    protected $fillable = 
    [
        'notes_groups_id', 'title', 'description', 'dashboard'
    ];

    public static function getDashboardNotes()
    {
        $ids = Notes::select('notes.notes_groups_id')->where('dashboard', '=', 1)->distinct('notes_groups_id')->get()->pluck('notes_groups_id')->all();
        $notes = [];
        
        foreach($ids as $id)
        {
            $group = NotesGroups::find($id);

            $notes[] = 
            [
                'category' => $group['name'],
                'items' => Notes::where('dashboard', '=', 1)->where('notes_groups_id', '=', $id)->get()
            ];
        }

        return $notes;
    }
}

app/Http/Controllers/Admin/NotesController.php
<?php

namespace App\Http\Controllers\Admin;

use Auth;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Facades\Validator;
use Illuminate\Validation\Rule;
use App\Http\Controllers\AdminController;
use App\Notes;
use App\NotesGroups;

class NotesController extends AdminController
{
    public function __construct()
    {
        $this->middleware('auth:admin');

        parent::__construct('notes');
    }

    public function index()
    {
        $this->init();

        $app = $this->app;
        $grid = Notes::select('notes.id', 'notes.title', 'notes_groups.name as notes_groups_name')
                    ->join('notes_groups', 'notes.notes_groups_id', '=', 'notes_groups.id')
                    ->paginate(10);

        return view('admin.notes.index', compact('app', 'grid'));
    }

    public function create(Request $request)
    {
        $this->init();

        $app = $this->app;
        $app['current']['title'] = 'Dodaj nową notatkę';

        $notesGroups = NotesGroups::orderBy('name')->get()->pluck('name', 'id')->all();

        return view('admin.notes.create', compact('app', 'notesGroups'));
    }

    public function store(Request $request)
    {
        $messages = $this->validatorMessages(
        [
            'title.required', 
        ]);

        $validator = Validator::make($request->all(), 
        [
            'title' => 'required',
        ], $messages);

        if ($validator->fails()) 
        {
            return redirect()->back()->withErrors($validator)->withInput();
        }
        
        $input = $request->all();
        $insert = Notes::create($input);
        
        return redirect()->route('admin.notes.index', ['id' => $insert->id])->with('success','Wpis dodany pomyślnie');
    }

    public function edit($id)
    {
        $this->init();

        $app = $this->app;
        $app['current']['title'] = 'Edytuj notatkę';

        $edit = Notes::find($id);

        $notesGroups = NotesGroups::orderBy('name')->get()->pluck('name', 'id')->all();

        return view('admin.notes.edit', compact('app', 'edit', 'notesGroups'));
    }

    public function update($id, Request $request)
    {
        $messages = $this->validatorMessages(
        [
            'title.required', 
        ]);

        $validator = Validator::make($request->all(), 
        [
            'title' => 'required',
        ], $messages);

        if ($validator->fails()) 
        {
            return redirect()->back()->withErrors($validator)->withInput();
        }

        $input = $request->all();

        $update = Notes::find($id);
        $update->update($input);

        return redirect()->route('admin.notes.edit', ['id' => $update->id])->with('success','Wpis zaktualizowany pomyślnie');
    }

    public function destroy($id)
    {
        $delete = Notes::find($id);
        $delete->delete();

        return redirect()->route('admin.notes.index')->with('success', 'Wpis został usunięty');
    }
}

resources/views/admin/notes/create.blade.php
@extends('admin.layout')

@section('content')

    <form method="POST" action="{{ route('admin.notes.create.submit') }}">
        @csrf
        <div class="card-body white-background silver-border radius-border-top">

            <div class="form-group {{ AdminHelper::DisplayErrorsClass($errors, 'title', 'input-error jq-input-error') }}">
                <label for="name">Tytuł</label>
                <input type="text" class="form-control" id="title" name="title" placeholder="" value="{{ old('title') }}">
            </div>

            <div class="form-group">
                <label for="email">Grupa</label>
                <select class="form-control" name="notes_groups_id">
                    @foreach($notesGroups as $key => $val)
                        <option value="{{ $key }}">{{ $val }}</option>
                    @endforeach
                </select>
            </div>

            <div class="form-group {{ AdminHelper::DisplayErrorsClass($errors, 'description', 'input-error jq-input-error') }}">
                <label for="email">Opis</label>
                <textarea class="summernote400 form-control" name="description" id="description" placeholder="">{{ !empty(old('description')) ? old('description') : "" }}</textarea>
            </div>

            <div class="form-group">
                <label for="dashboard">Pokaż na stronie głównej</label>
                <select class="form-control" name="dashboard">
                    <option value="0">Nie</option>
                    <option value="1">Tak</option>
                </select>
            </div>

        </div>
        <div class="card-footer silver-border radius-border-bottom">
            <button type="submit" class="btn btn-primary">Zapisz</button>
        </div>
    </form>

@endsection

resources/views/admin/notes/edit.blade.php
@extends('admin.layout')

@section('content')

    <form method="POST" action="{{ route('admin.notes.edit.submit', $edit->id) }}">
        @csrf
        <input name="_method" type="hidden" value="PUT">
        <div class="card-body white-background silver-border radius-border-top">

            <div class="form-group {{ AdminHelper::DisplayErrorsClass($errors, 'title', 'input-error jq-input-error') }}">
                <label for="title">Tytuł</label>
                <input type="text" class="form-control" id="title" name="title" placeholder="" value="{{ !empty(old('title')) ? old('title') : $edit->title }}">
            </div>

            <div class="form-group">
                <label for="email">Grupa</label>
                <select class="form-control" name="notes_groups_id">
                    @foreach($notesGroups as $key => $val)
                    <option value="{{ $key }}" @if($key == $edit->notes_groups_id) selected @endif>{{ $val }}</option>
                    @endforeach
                </select>
            </div>

            <div class="form-group {{ AdminHelper::DisplayErrorsClass($errors, 'description', 'input-error jq-input-error') }}">
                <label for="email">Opis</label>
                <textarea class="summernote400 form-control" name="description" id="description" placeholder="">{{ !empty(old('description')) ? old('description') : $edit->description }}</textarea>
            </div>

            <div class="form-group">
            <label for="dashboard">Pokaż na stronie głównej</label>
                <select class="form-control" name="dashboard">
                    <option value="0" @if(0 == $edit->dashboard) selected @endif>Nie</option>
                    <option value="1" @if(1 == $edit->dashboard) selected @endif>Tak</option>
                </select>
            </div>

        </div>
        <div class="card-footer silver-border radius-border-bottom">
            <button type="submit" class="btn btn-primary">Zapisz</button>
        </div>
    </form>

@endsection

resources/views/admin/notes/index.blade.php
@extends('admin.layout')

@section('content')

    <table class="table table-grid radius-border">
        <tbody>
            <tr>
                <th>Nazwa</th>
                <th>Grupa</th>
                <th></th>
            </tr>
            @foreach ($grid as $key => $item)
            <tr>
                <td>{{ $item->title }}</td>
                <td>{{ $item->notes_groups_name }}</td>
                <td class="text-right">
                    <a class="btn btn-sm btn-primary" href="{{ route('admin.notes.edit', $item->id) }}" title="Edytuj"><i class="fas fa-pencil-alt"></i></a>
                    <a class="btn btn-sm btn-danger jq-popup-congrim" data-submit-class="jq-delete-items-form-{{ $item->id }}" href="#" title="Usuń"><i class="fas fa-trash-alt"></i></a>
                    <form method="POST" action="{{ route('admin.notes.destroy', $item->id) }}" class="jq-delete-items-form-{{ $item->id }}">
                        <input name="_method" type="hidden" value="DELETE">
                        @csrf
                    </form>
                </td>
            </tr>
            @endforeach
        </tbody>
    </table>

    {{ $grid->render() }}

@endsection